name: "Copilot Setup Steps"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/vcpkg_cache,readwrite

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Common Setup
        uses: ./.github/actions/linux-setup
        with:
          buildfolder: out/build/Clang/Release
          compiler: clang

      - name: Make tools directory
        run: mkdir -p ./tools

      - name: Install code-checker dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y cppcheck hotspot iwyu libunwind-dev libelf-dev libdw-dev libboost-all-dev

      - name: Install Infer static analyzer
        run: |
          cd ./tools && \
          VERSION=1.2.0; \
          curl -SL "https://github.com/facebook/infer/releases/download/v$VERSION/infer-linux-x86_64-v$VERSION.tar.xz" \
          | sudo tar -C /opt -xJ && \
          sudo ln -s "/opt/infer-linux-x86_64-v$VERSION/bin/infer" /usr/local/bin/infer && \
          cd ..

      - name: Install heaptrack
        run: |
          cd ./tools && \
          git clone https://github.com/KDE/heaptrack.git && \
          cd heaptrack && \
          mkdir build && \
          cd build && \
          cmake -DCMAKE_BUILD_TYPE=Release .. && \
          make -j$(nproc) && \
          cd ../../../

      - name: Install ClangBuildAnalyzer
        run: |
          cd ./tools && \
          git clone https://github.com/aras-p/ClangBuildAnalyzer.git && \
          cd ClangBuildAnalyzer && \
          make -f projects/make/Makefile && \
          cd ../..

      - name: Set Environment Variable for vcpkg
        run: echo "VCPKG_BINARY_SOURCES=clear;files,/home/runner/work/WhiskerToolbox/WhiskerToolbox/vcpkg_cache,readwrite" >> $GITHUB_ENV

      - name: Configure CMake without coverage
        run: cmake --preset linux-clang-release -DENABLE_ORTOOLS=OFF -DENABLE_TIME_TRACE=ON -DENABLE_FUZZ_TESTING=ON

      - name: Build
        run: cmake --build --preset linux-clang-release